name: Release Windows Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Bili_Video/requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Install GitVersion
      run: |
        curl -sSL https://github.com/GitTools/GitVersion/releases/download/v5.6.5/gitversion_5.6.5_windows_x64.zip -o gitversion.zip
        unzip gitversion.zip -d gitversion
        mv gitversion/gitversion.exe /usr/local/bin/

    - name: Get version using GitVersion
      id: version
      run: |
        VERSION=$(gitversion /showvariable SemVer)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Build Windows executable
      run: |
        cd Bili_Video
        pyinstaller --windowed --onefile --icon=icon.ico --name="A+1-Tool" --hidden-import=resources --hidden-import=download --hidden-import=m4s gui.py

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: Bili_Video/dist/*
        tag_name: ${{ env.VERSION }}

    - name: Clean up
      run: |
        rm -rf Bili_Video/build
        rm -rf Bili_Video/dist
